name:                hlesspass
version:             0.1.0
github:              "Bannerets/hlesspass"
license:             MIT
author:              "Bannerets <comonoid@protonmail.com>"
maintainer:          "comonoid@protonmail.com"
copyright:           "2019 Bannerets <comonoid@protonmail.com>"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Bannerets/hlesspass#readme>

dependencies:
- base >= 4.7 && < 5
- unix
- process
- directory
- bytestring
- memory
- cryptonite
- cmdargs

ghc-options:
- -Wincomplete-patterns

library:
  source-dirs: lib

executables:
  hlesspass:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hlesspass

tests:
  hlesspass-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hspec
    - hlesspass
